base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "frank130845"
repo_name: "llm-arxiv-dailyyw"
show_authors: True
show_links: True
max_results: 10

publish_readme: True
publish_gitpage: True

json_readme_path: './docs/llm-arxiv-daily.json'
json_gitpage_path: './docs/llm-arxiv-daily-web.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'

# keywords to search
keywords:
    "LLM Reasoning":
        filters: ["LLM Reasoning", "LLM Thinking", "LLM Causal Reasoning", "LLM Commonsense Reasoning", "LLM Logical Reasoning", "Multimodal Reasoning", "MLLM Reasoning", "VLM Reasoning", "Multimodal LLM Reasoning"]
    # "LLM Evaluation":
    #     filters: ["LLM Evaluation", "Benchmark", "Vision-Language Benchmark", "LLM Benchmark", "LLM Evaluation Metric", "LLM Evaluation Protocol", "LLM Evaluation Dataset"]
    # "LLM MLLM":
    #     filters: ["LLM", "Large Language Model", "MLLM", "Multi-modal Large Language Model", "Large Vision-Language Model", "Foundation Model", "Universal Model", "General Model"]
    # "Video Understanding":
    #     filters: ["Video Understanding", "Video Caption", "Visual Language Navigation", "Video Question Answering", "Video Recognition", "Video Retrieval", "Video Generation"]
